#

In [1]:
import seaborn as snb

In [2]:
data=snb.load_dataset('iris')

In [3]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# Infercial Statestics

# Cetral Tendency

* Mean
    * Median
        * mode

In [13]:
data['sepal_length'].mean()

5.843333333333334

In [9]:
data.mean()

C:\Users\Dell\AppData\Local\Temp\ipykernel_17028\531903386.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.mean()

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [15]:
data['petal_length'].mode()

0    1.4
1    1.5
Name: petal_length, dtype: float64

In [16]:
data['sepal_length'].median()

5.8

In [23]:
data.skew()

C:\Users\Dell\AppData\Local\Temp\ipykernel_17028\1188251951.py:1: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.skew()

sepal_length    0.314911
sepal_width     0.318966
petal_length   -0.274884
petal_width    -0.102967
dtype: float64

In [27]:
data['sepal_length'].skew()

0.3149109566369728

In [25]:
data.kurt()

C:\Users\Dell\AppData\Local\Temp\ipykernel_17028\2907027414.py:1: FutureWarning: The default value of numeric_only in DataFrame.kurt is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.kurt()

sepal_length   -0.552064
sepal_width     0.228249
petal_length   -1.402103
petal_width    -1.340604
dtype: float64

In [26]:
data['sepal_length'].kurt()

-0.5520640413156395

In [24]:
data.cov()

C:\Users\Dell\AppData\Local\Temp\ipykernel_17028\4020818503.py:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.cov()

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      0.685694    -0.042434      1.274315     0.516271
sepal_width      -0.042434     0.189979     -0.329656    -0.121639
petal_length      1.274315    -0.329656      3.116278     1.295609
petal_width       0.516271    -0.121639      1.295609     0.581006

In [21]:
data.corr()

C:\Users\Dell\AppData\Local\Temp\ipykernel_17028\2627137660.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [28]:
import warnings
warnings.filterwarnings('ignore')

In [32]:
# range
minn=data['sepal_length'].min()
maxx = data['sepal_length'].max()

rangee=maxx-minn
rangee

3.6000000000000005

In [35]:
# range
range=data["sepal_length"].max()-data["sepal_length"].min()
print(range)

3.6000000000000005

In [33]:
# varience
data['sepal_length'].var()

0.6856935123042505

In [44]:
data['sepal_length'].cov()

TypeError: Series.cov() missing 1 required positional argument: 'other'

In [43]:
data['sepal_length'].corr()

TypeError: Series.corr() missing 1 required positional argument: 'other'

In [34]:
data['sepal_length'].std()

0.8280661279778629

In [37]:
# skwness
data['sepal_length'].skew()

0.3149109566369728

In [38]:
# kurtosis
data['sepal_length'].kurt()

-0.5520640413156395

In [39]:
q1=data['sepal_length'].quantile(0.25)
q2=data['sepal_length'].quantile(0.50)
q3=data['sepal_length'].quantile(0.75)

In [40]:
# IQR
IQR=q3-q1
IQR

1.3000000000000007

In [41]:
# covarience
data.cov()

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      0.685694    -0.042434      1.274315     0.516271
sepal_width      -0.042434     0.189979     -0.329656    -0.121639
petal_length      1.274315    -0.329656      3.116278     1.295609
petal_width       0.516271    -0.121639      1.295609     0.581006

In [42]:
# Corelation
data.corr()

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [46]:
data.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# Descriptive Statistics